INSERT INTO PRODUTO(DESCRICAO, VALOR) VALUES('Produto 1', 10.0);
INSERT INTO PRODUTO(DESCRICAO, VALOR) VALUES('Produto 2', 14.0);
INSERT INTO PRODUTO(DESCRICAO, VALOR) VALUES('Produto 3', 16.0);
INSERT INTO PRODUTO(DESCRICAO, VALOR) VALUES('Produto 4', 18.0);
INSERT INTO PRODUTO(DESCRICAO, VALOR) VALUES('Produto 5', 11.0);

INSERT INTO PESSOA(EMAIL, TELEFONE, TIPO, NOME, CPF) VALUES('jose@email.com', '63981000000' ,'F', 'José da Silva', '74793108032');
INSERT INTO PESSOA(EMAIL, TELEFONE, TIPO, RAZAO_SOCIAL, CNPJ) VALUES('maria@email.com', '6332150000' ,'J', 'Maria de Sousa Ltda.', '21871035000176');

INSERT INTO VENDA(DATA, PESSOA_ID) VALUES(CURRENT_TIMESTAMP(), 1);
INSERT INTO VENDA(DATA, PESSOA_ID) VALUES(CURRENT_TIMESTAMP(), 2);

INSERT INTO ITEM_VENDA(VENDA_ID, PRODUTO_ID, QTD) VALUES(1, 1, 1);
INSERT INTO ITEM_VENDA(VENDA_ID, PRODUTO_ID, QTD) VALUES(1, 2, 5);
INSERT INTO ITEM_VENDA(VENDA_ID, PRODUTO_ID, QTD) VALUES(2, 3, 3);
INSERT INTO ITEM_VENDA(VENDA_ID, PRODUTO_ID, QTD) VALUES(1, 4, 7);
INSERT INTO ITEM_VENDA(VENDA_ID, PRODUTO_ID, QTD) VALUES(2, 5, 2);
